jellyseer:
  api_url: "http://192.168.1.2:5055/api/v1"
  # Local jellyseeer account with admin rights
  email: "user@example.com"
  password: "password"

whitelisted_users:
  - alice
  - bob

retention_days:
  movies: 30
  tv: 60

dry_run: true  # false = delete permanently
